### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by Michele-Rawlins** [nss-evening-cohort-11/bands-easybakeoven#11]
**User Story**
As a  user , I should see icons on bottom of page in the footer.

**AC**
WHEN any page loads
THEN  I should see icons on the footer below
AND those icons should be clickable
AND they should be stored in a file

**Dev Notes**

- Create a folder for icon pngs
- Link folder to all pages

**Comment by zoeames** [comment]
duplicate ticket - looks like this work is addressed in #3
